# Generated by Django 3.2.3 on 2024-08-04 07:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240722_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Игредиент для рецепта', 'verbose_name_plural': 'Игредиенты для рецепта'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Должен состоять из букв, цифр, знака подчеркивания или тире', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='\n    Слаг должен состоять только из букв, цифр, знаков подчеркивания или тире.\n    ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Уникальный слаг'),
        ),
    ]
