# Generated by Django 3.2.3 on 2024-08-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20240807_2117'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_name_ingredients',
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
