# Generated by Django 3.2.3 on 2024-08-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20240807_2147'),
    ]

    operations = [
    ]
